const { db } = require('../config/firebase');
const ledgerRemainderService = require('./ledgerRemainder');
const ledgerLogsService = require('./ledgerLogs');

/**
 * Parse date in DD/MM/YYYY format to ISO string
 * Accepts format: dd/mm/yyyy (4-digit year required)
 * Rejects: dd/mm/yy (2-digit year)
 */
function parseDateFormat(dateStr) {
  if (!dateStr) return '';

  // If xlsx parses the cell as an actual Date, accept it.
  if (dateStr instanceof Date) {
    if (isNaN(dateStr.getTime())) return '';
    return dateStr.toISOString().slice(0, 10);
  }

  // If it's an Excel serial date (number), try convert.
  if (typeof dateStr === 'number' && Number.isFinite(dateStr)) {
    // Excel serial dates are typically in the ~40000-60000 range for modern years.
    // If it looks reasonable, convert using the common JS epoch mapping.
    if (dateStr > 1000 && dateStr < 100000) {
      const utc = new Date(Date.UTC(1899, 11, 30) + dateStr * 86400000);
      if (!isNaN(utc.getTime())) return utc.toISOString().slice(0, 10);
    }
    return '';
  }

  if (typeof dateStr !== 'string') return '';

  const s = dateStr.trim();
  if (!s) return '';

  // Accept ISO YYYY-MM-DD directly.
  if (/^\d{4}-\d{2}-\d{2}$/.test(s)) return s;

  // Match only dd/mm/yyyy or dd-mm-yyyy format (4-digit year REQUIRED)
  const dateRegex = /^(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{4})$/;
  const match = s.match(dateRegex);

  if (match) {
    const day = parseInt(match[1], 10);
    const month = parseInt(match[2], 10);
    const year = parseInt(match[3], 10);

    // Validate date
    if (month < 1 || month > 12 || day < 1 || day > 31) {
      return '';
    }

    // Return ISO format (YYYY-MM-DD)
    return `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
  }

  // Fallback: try JS Date parsing for strings like "2026-03-29T00:00:00Z"
  const parsed = new Date(s);
  if (!isNaN(parsed.getTime())) return parsed.toISOString().slice(0, 10);

  return '';
}

class OutstandingService {
  /**
   * Process outstanding records from Excel
   * 1. Validates against Ledger_Remainder collection
   * 2. Updates ledger with new debit/credit/date/comments values
   * 3. Creates log entries for audit trail
   * 4. Returns validation results
   */
  async processOutstandingRecords(validRecords, userId = null, fileName = null) {
    const results = {
      processed: 0,
      found: [],
      notFound: [],
      updated: 0,
      logsCreated: 0,
    };

    if (!validRecords.length) {
      return results;
    }

    const logsToCreate = [];

    // Process each record
    for (const record of validRecords) {
      try {
        // Search for matching ledger_id in Ledger_Remainder
        // ledger_id is generated by removing spaces from ledger name
        const ledgerId = String(record.ledger || '')
          .trim()
          .replace(/\s+/g, '');

        if (!ledgerId) {
          results.notFound.push({
            ledger: record.ledger,
            reason: 'Invalid ledger name',
          });
          continue;
        }

        // Find the ledger in Ledger_Remainder
        const ledgerSnapshot = await db
          .collection('Ledger_Remainder')
          .where('ledger_id', '==', ledgerId)
          .limit(1)
          .get();

        if (ledgerSnapshot.empty) {
          results.notFound.push({
            ledger: record.ledger,
            ledger_id: ledgerId,
            reason: 'Ledger master not found',
          });
          continue;
        }

        // Get existing ledger document
        const ledgerDoc = ledgerSnapshot.docs[0];
        const ledgerRef = ledgerDoc.ref;
        const ledgerData = ledgerDoc.data();

        // Store previous values for audit trail
        const previousDebit = ledgerData.debit || 0;
        const previousCredit = ledgerData.credit || 0;

        // Parse date format (dd/mm/yyyy to yyyy-mm-dd)
        const parsedDate = parseDateFormat(record.date);

        // Update ledger with new values (REPLACE, not increment)
        const updateData = {
          debit: parseFloat(record.debit || 0) || 0,
          credit: parseFloat(record.credit || 0) || 0,
          group: String(record.group || '').trim() || ledgerData.group,
          lastUpdatedAt: new Date().toISOString(),
          updatedByUserId: userId || null,
          sourceFileName: fileName || null,
        };

        // Always store date if it exists (dd/mm/yyyy format)
        if (parsedDate) {
          updateData.lastTransactionDate = parsedDate;
        }
        
        // Always store comments (even if empty)
        updateData.lastComments = String(record.comments || '').trim();

        await ledgerRef.update(updateData);

        results.updated += 1;

        // Create audit log entry
        logsToCreate.push({
          ledger_id: ledgerId,
          ledger_name: ledgerData.ledger_name,
          group: String(record.group || '').trim() || ledgerData.group,
          debit: parseFloat(record.debit || 0) || 0,
          credit: parseFloat(record.credit || 0) || 0,
          date: parsedDate || String(record.date || '').trim(),
          comments: String(record.comments || '').trim(),
          previous_debit: previousDebit,
          previous_credit: previousCredit,
          operation: (previousDebit === 0 && previousCredit === 0) ? 'insert' : 'update',
          userId,
        });

        results.found.push({
          ledger: record.ledger,
          ledger_id: ledgerId,
          debit: parseFloat(record.debit || 0) || 0,
          credit: parseFloat(record.credit || 0) || 0,
          date: parsedDate || record.date,
          comments: record.comments,
        });

        results.processed += 1;
      } catch (error) {
        console.error('Error processing outstanding record:', error);
        results.notFound.push({
          ledger: record.ledger,
          reason: `Error: ${error.message}`,
        });
      }
    }

    // Create all logs in batch
    if (logsToCreate.length) {
      try {
        const logResult = await ledgerLogsService.addLogs(logsToCreate);
        results.logsCreated = logResult.inserted;
      } catch (error) {
        console.error('Error creating logs:', error);
      }
    }

    return results;
  }

  /**
   * Get outstanding summary for a ledger
   */
  async getSummary(ledger_id) {
    try {
      const ledgerDoc = await db
        .collection('Ledger_Remainder')
        .where('ledger_id', '==', ledger_id)
        .limit(1)
        .get();

      if (ledgerDoc.empty) {
        return null;
      }

      const data = ledgerDoc.docs[0].data();
      const logs = await ledgerLogsService.getLogsByLedgerId(ledger_id, { limit: 50 });

      return {
        ledger_id,
        ledger_name: data.ledger_name,
        city: data.city,
        debit: data.debit || 0,
        credit: data.credit || 0,
        logs,
      };
    } catch (error) {
      console.error('Error fetching summary:', error);
      return null;
    }
  }
}

module.exports = new OutstandingService();
